#!/bin/bash
yum update -y
yum install httpd php php-mysql stress -y
cd /etc/httpd/conf
cp httpd.conf httpdconfbackup.conf
rm -rf httpd.conf
wget https://s3.amazonaws.com/breadtechs2017config/httpd.conf
cd /var/www/html
echo "healthy" > healthy.html
wget https://wordpress.org/latest.tar.gz
tar -xzf latest.tar.gz
cp -r wordpress/* /var/www/html/
rm -rf wordpress
rm -rf latest.tar.gz
chmod -R 755 wp-content
chown -R apache.apache wp-content
service httpd start
chkconfig httpd on


aws s3 cp --recursive s3://wordpresscode2017bread /var/www/html/
cd /var/www/html
chmod -R 755 wp-content
chown -R apache.apache wp-content
wget https://s3.amazonaws.com/breadtechs2017config/htaccess
cp htaccess .htaccess
rm -rf htaccess
service httpd restart


0/2 * * * * root aws s3 sync --delete /var/www/html/ s3://workpresscode2017bread/
0/2 * * * * root aws s3 sync --delete /var/www/html/wp-content/uploads/ s3://workpressmedia2017bread/
0/3 * * * * root aws s3 sync --delete s3://workpresscode2017bread/ /var/www/html/

#!/bin/bash
yum update -y
aws s3 sync --delete s3://workpresscode2017bread/ /var/www/html/

stress --cpu 100
